-- Insert sample job postings for testing
-- Run this SQL script to populate the job_postings table

INSERT INTO job_postings (
    farmer_id, farmer_name, farmer_email, farmer_phone, farmer_location,
    job_title, job_type, job_category, job_description,
    workers_needed, wage_per_day, duration_days, start_date, end_date,
    location, work_hours_per_day,
    requirements, responsibilities,
    accommodation_provided, food_provided, transportation_provided, 
    tools_provided, other_benefits, status
) VALUES 
-- Job 1: Rice Harvesting Worker
(
    1,
    'Ramesh Kumar',
    'ramesh@agrohub.com',
    '+91 98765 43210',
    'Mysore, Karnataka',
    'Rice Harvesting Worker',
    'seasonal',
    'harvesting',
    'We are looking for experienced workers to help with rice harvesting on our 10-acre farm. The work involves traditional harvesting methods using sickles, bundling the harvested crop, and transporting it to the threshing area.',
    5,
    800.00,
    3,
    DATE_ADD(CURDATE(), INTERVAL 2 DAY),
    DATE_ADD(CURDATE(), INTERVAL 5 DAY),
    'Mysore, Karnataka',
    8,
    '["Experience with traditional rice harvesting methods","Ability to work 8-10 hours daily in field conditions","Physical fitness to handle manual labor","Knowledge of proper harvesting techniques to minimize crop damage"]',
    '["Harvest rice crops using traditional methods","Bundle and organize harvested crops properly","Transport bundles to designated collection points","Maintain quality standards during harvesting"]',
    1,
    1,
    0,
    1,
    'Free lunch and evening snacks provided. Bonus payment upon completion of work.',
    'active'
),
-- Job 2: Tractor Operator
(
    1,
    'Suresh Patil',
    'suresh@agrohub.com',
    '+91 98123 45678',
    'Mandya, Karnataka',
    'Tractor Operator',
    'contract',
    'machine_operation',
    'Looking for a skilled tractor operator for plowing 20 acres of land. Must have valid driving license and at least 2+ years of experience operating farm tractors.',
    1,
    1500.00,
    5,
    DATE_ADD(CURDATE(), INTERVAL 7 DAY),
    DATE_ADD(CURDATE(), INTERVAL 12 DAY),
    'Mandya, Karnataka',
    8,
    '["Valid driving license for agricultural vehicles","Minimum 2 years of tractor operation experience","Knowledge of modern tillage equipment","Ability to perform basic tractor maintenance"]',
    '["Operate tractor for plowing 20 acres of land","Perform daily equipment checks","Ensure proper fuel management","Report any mechanical issues immediately"]',
    0,
    1,
    1,
    1,
    'All equipment and fuel provided. Accommodation allowance of ₹200/day if needed.',
    'active'
),
-- Job 3: Crop Planting Assistant
(
    1,
    'Mahesh Gowda',
    'mahesh@agrohub.com',
    '+91 97654 32109',
    'Bangalore Rural',
    'Crop Planting Assistant',
    'temporary',
    'planting',
    'Help us with vegetable crop planting. Basic farming knowledge required. Training will be provided for specific crops.',
    3,
    750.00,
    2,
    DATE_ADD(CURDATE(), INTERVAL 3 DAY),
    DATE_ADD(CURDATE(), INTERVAL 5 DAY),
    'Bangalore Rural',
    7,
    '["Basic farming knowledge","Physical fitness for outdoor work","Willingness to learn"]',
    '["Help with vegetable crop planting","Prepare soil beds","Follow planting guidelines","Water newly planted crops"]',
    0,
    1,
    1,
    1,
    NULL,
    'active'
),
-- Job 4: Irrigation System Operator
(
    1,
    'Krishna Reddy',
    'krishna@agrohub.com',
    '+91 99876 54321',
    'Hassan, Karnataka',
    'Irrigation System Operator',
    'contract',
    'irrigation',
    'Operate and maintain drip irrigation system for sugarcane fields. Knowledge of modern irrigation techniques preferred.',
    2,
    1200.00,
    7,
    DATE_ADD(CURDATE(), INTERVAL 4 DAY),
    DATE_ADD(CURDATE(), INTERVAL 11 DAY),
    'Hassan, Karnataka',
    8,
    '["Knowledge of drip irrigation systems","Basic plumbing skills","Ability to identify and fix minor leaks"]',
    '["Operate drip irrigation system daily","Monitor water flow and pressure","Perform routine maintenance","Keep irrigation schedule logs"]',
    1,
    1,
    0,
    1,
    'Free accommodation in farm quarters with electricity and water.',
    'active'
),
-- Job 5: Pesticide Spray Operator
(
    1,
    'Venkatesh Naik',
    'venkatesh@agrohub.com',
    '+91 96543 21098',
    'Tumkur, Karnataka',
    'Pesticide Spray Operator',
    'daily_wage',
    'pest_control',
    'Looking for 1 day spray work for pesticide application on cotton fields. Must have experience with spray equipment.',
    1,
    900.00,
    1,
    DATE_ADD(CURDATE(), INTERVAL 1 DAY),
    DATE_ADD(CURDATE(), INTERVAL 1 DAY),
    'Tumkur, Karnataka',
    6,
    '["Experience with pesticide spray equipment","Knowledge of safety protocols","Physical fitness"]',
    '["Apply pesticides to cotton crops","Ensure proper coverage","Follow safety guidelines","Clean equipment after use"]',
    0,
    1,
    1,
    1,
    'Safety equipment provided including mask, gloves, and protective clothing.',
    'active'
);
